contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here (this pipeline is built from the nf-core template)
  - name: "GitHub Discussions"
    url: https://github.com/aerusakovich/nanocirc_pipeline/issues
    about: Discussion about the nanocirc pipeline
